services:
  - type: web
    name: voice-qa-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT app:app
    plan: free