services:
  - type: web
    name: voice-qa-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PORT
        value: 5000